version: "3"
services:
    backend:
        restart: always
        build: ../backend/
        depends_on:
            - postgres
            - redis
        expose:
            - "8000"
        links:
            - postgres:postgres
            - redis:redis
        networks: 
          - all-network
        volumes:
            - ../vols/staticfiles:/app/staticfiles
            - ../vols/media:/app/media
            - ../backend:/app
        command: /bin/sh -c "python3 /app/manage.py migrate && python3 /app/manage.py collectstatic --no-input && python3 /app/manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./dev.env
    celery-worker:
        build: ../backend/
        command: celery -A project worker -l info
        volumes:
            - ../vols/media:/app/media
            - ../backend:/app
        depends_on:
            - postgres
            - redis
        links:
            - postgres:postgres
            - redis:redis
        networks: 
          - all-network
        env_file:
            - ./dev.env
    nginx:
        image: "nginx"
        restart: always
        volumes:
          - ../nginx:/etc/nginx/conf.d
          - ../vols/staticfiles:/var/www/app/static
          - ../vols/media:/var/www/app/media
        ports:
          - "80:80"
        networks: 
          - all-network

    postgres:
        image: "postgres:10.3-alpine"
        restart: unless-stopped
        env_file:
          - ./dev.env
        ports:
          - "5432:5432"
        volumes:
          - ../postgres/data:/var/lib/postgresql/data
        networks: 
          - all-network

    redis:
        restart: always
        image: redis:latest
        expose:
        - "6379"
        networks: 
          - all-network

networks:
    all-network:
        driver: "bridge"
