version: "3"
services:
    backend:
        image: "booksforfriends/backend"
        restart: always
        depends_on:
            - postgres
            - redis
        expose:
            - "8000"
        links:
            - postgres:postgres
            - redis:redis
        networks: 
          - all-network
        volumes:
            - ../vols/staticfiles:/app/staticfiles
            - ../vols/media:/app/media
            - ../vols/frontend-build/webpack-stats:/app/apps/frontend/webpack-stats
            - ../vols/frontend-build/static:/app/apps/frontend/static/frontend/app
        command: /bin/sh -c "python3 /app/manage.py migrate && python3 /app/manage.py collectstatic --clear --no-input && /usr/bin/gunicorn project.wsgi:application -w 2 -b :8000"
        env_file:
            - ./.env
    celery-worker:
        image: "booksforfriends/backend"
        command: celery -A project worker -l info
        volumes:
            - ../vols/media:/app/media
        depends_on:
            - postgres
            - redis
        links:
            - postgres:postgres
            - redis:redis
        networks: 
          - all-network
        env_file:
        - ./.env
    nginx:
        image: "nginx"
        restart: always
        volumes:
          - ../nginx:/etc/nginx/conf.d
          - ../vols/media:/var/www/app/media
          - ../vols/staticfiles:/var/www/app/static
          - ../vols/vue:/var/www/app/vue
        ports:
          - "80:80"
        networks: 
          - all-network
        ports:
          - "80:80"
        networks: 
          - all-network

    postgres:
        image: "postgres:10.3-alpine"
        restart: unless-stopped
        env_file:
          - ./.env
        ports:
          - "5432:5432"
        volumes:
          - ../postgres/data:/var/lib/postgresql/data
        networks: 
          - all-network
        networks: 
          - all-network
    redis:
        restart: always
        image: redis:latest
        expose:
        - "6379"
        networks: 
          - all-network

networks:
    all-network:
        driver: "bridge"
